FROM bitnami/spark:3.3.1

USER root

# Copy the MinIO reader script
COPY scripts/read_from_minio.py /opt/bitnami/spark/

# Set the working directory
WORKDIR /opt/bitnami/spark


# Run the MinIO reader
CMD ["spark-submit", "--packages", "io.delta:delta-core_2.12:2.2.0,org.apache.hadoop:hadoop-aws:3.3.1"]
