FROM python:3.9-slim

WORKDIR /app

# Install required packages
RUN pip install confluent-kafka[avro]

# Copy the consumer script
COPY scripts/kafka_consumer.py /app/

# Run the consumer script
CMD ["python", "kafka_consumer.py"]
