FROM python:3.9-slim

WORKDIR /app

# Innstall required packages
RUN pip install requests

# Copy the configuration script
COPY script/configure_debezium.py /app/

# Run the configuration script
CMD ["python", "configure_debezium.py"]